[0m11:05:12.762780 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ADF1596890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ADF1596550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ADF1596490>]}


============================== 11:05:12.769009 | 263a4d72-9b8a-4ea2-8734-60b56bc39c88 ==============================
[0m11:05:12.769009 [info ] [MainThread]: Running with dbt=1.7.18
[0m11:05:12.771008 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\Hasan\\OneDrive\\Desktop\\dbt-mysql\\sqlpro\\logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Hasan\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m11:05:12.778003 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'sqlpro'
[0m11:05:12.780002 [debug] [MainThread]: Command `dbt run` failed at 11:05:12.780002 after 0.11 seconds
[0m11:05:12.781001 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ADEA6ABF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ADF15E6BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ADF15E5310>]}
[0m11:05:12.782001 [debug] [MainThread]: Flushing usage events
