[0m15:19:04.565973 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002855F8E5A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028562433AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028562433CA0>]}


============================== 15:19:04.574838 | 8f50e65b-1ac3-4d80-96b9-04cdcffeb5c2 ==============================
[0m15:19:04.574838 [info ] [MainThread]: Running with dbt=1.7.18
[0m15:19:04.576826 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Hasan\\.dbt', 'log_path': 'C:\\Users\\Hasan\\OneDrive\\Desktop\\dbt-mysql\\my_sql\\logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:19:04.582822 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'my_sql'
[0m15:19:04.584823 [debug] [MainThread]: Command `dbt run` failed at 15:19:04.584823 after 0.15 seconds
[0m15:19:04.586820 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002855F8E5A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028562432980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028562432D40>]}
[0m15:19:04.588820 [debug] [MainThread]: Flushing usage events
